# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uri', models.CharField(max_length=63)),
                ('lang', models.CharField(blank=True, max_length=15, null=True)),
                ('code', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Code History',
            },
        ),
        migrations.CreateModel(
            name='CodeUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uri', models.CharField(max_length=63, unique=True)),
                ('lang', models.CharField(blank=True, choices=[(b'C', b'C'), (b'CPP', b'C++'), (b'JAVA', b'Java'), (b'PYTHON', b'Python')], max_length=15, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
